### ISSUE TITLE
Deploy to another region

### ISSUE THREAD

**Issue by cncolder** [aliyun/serverless-aliyun-function-compute#14]
First, thanks this repo. I cannot waiting this merge to `serverless` plugins.

I have deploy my hello demo to default `cn-shanghai` region.
But I cannot configure `serverless.yml` deploy to another region like `cn-beijing`.
The `runtime` section not work also.

```yml
# serverless.yml
service: hello

provider:
  name: aliyun
  credentials: ~/.aliyuncli/credentials # path must be absolute
  region: cn-beijing
  runtime: nodejs8

plugins:
  - serverless-aliyun-function-compute
```

```json5
// .serverless/configuration-template-create.json
{
  "Resources": {
    "sls-storage-bucket": {
      "Type": "ALIYUN::OSS:Bucket",
      "Properties": {
        "BucketName": "sls-hello",
        "Region": "cn-shanghai"
      }
    },
    "sls-function-service": {
      "Type": "ALIYUN::FC::Service",
      "Properties": {
        "name": "hello-dev",
        "region": "cn-shanghai",
        "logConfig": {
          "logstore": "hello-dev",
          "project": "sls-hello-logs"
        }
      }
    }
  }
}
```

```json5
// .serverless/configuration-template-update.json
    "sls-hello-dev-hello": {
      "Type": "ALIYUN::FC::Function",
      "Properties": {
        "name": "hello-dev-hello",
        "service": "hello-dev",
        "handler": "index.hello",
        "memorySize": 128,
        "timeout": 30,
        "runtime": "nodejs6",
        "code": {
          "ossBucketName": "sls-hello",
          "ossObjectName": "serverless/hello/dev/1517210161124-2018-01-29T07:16:01.124Z/hello.zip"
        }
      }
    }
```
