### ISSUE TITLE
之前用 1.0 ,另一个项目升级了 1.2 和 1.26.1 之后报错

### ISSUE THREAD

**Issue by buhe** [aliyun/serverless-aliyun-function-compute#21]
```
TypeError: Cannot read property 'split' of undefined
    at AliyunPackage.compileStorage (/xxx/node_modules/serverless-aliyun-function-compute/package/lib/compileFunctions.js:30:31)
    

tldr...

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.9.1
     Serverless Version:     1.26.1
```

**Comment by buhe** [comment]
用了 serverless 的 ts 模版和 serverless-webpack 插件

```
service:
  name: app

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-aliyun-function-compute

package:
  excludeDevDependencies: true
  exclude:
    - package-lock.json
    - .gitignore
    - yarn.lock
    - .git/**
    - test/**

provider:
  name: aliyun
  runtime: nodejs8
  credentials: ~/.aliyuncli/credentials # path must be absolute

functions:
  hello:
    handler: handler.test
    events:
      - http:
          method: post
          path: test
```

**Comment by buhe** [comment]
暂时没有动力升级了... 我有你微信，回头咱们微信聊

**Comment by buhe** [comment]
这个应该还是个问题，但是我 workaground 的了，

```
service:
  name: xxx
plugins:
  - serverless-webpack
  - serverless-aliyun-function-compute
package:
  artifact: .serverless/xxx.zip
```
xxx 就是 name 的名字，我没定位到原因，可能和我用了 webpack plugin 有关
xxx 是
