### ISSUE TITLE
provider.region 参数不能使用变量 使用之后命令会没有响应

### ISSUE THREAD

**Issue by lhr0909** [aliyun/serverless-aliyun-function-compute#55]
serverless.yml

```yaml
provider:
  name: aliyun
  region: ${opt:region, 'cn-zhangjiakou'}
```

这种情况会导致整个serverless命令没有响应
